spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://user-service:8081
          predicates:
            - Path=/auth/**
        - id: user-api-route
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**,/api/teams/**
        - id: game-data-route
          uri: http://game-data-service:8082
          predicates:
            - Path=/api/pokemon/**,/api/validate/**
        - id: lobby-route
          uri: http://lobby-service:8083
          predicates:
            - Path=/api/lobby/**
        - id: battle-http-route
          uri: http://battle-service:8084
          predicates:
            - Path=/api/battle/**
        - id: battle-ws-route
          uri: http://battle-service:8084
          predicates:
            - Path=/ws/battle/**
          metadata:
            response-timeout: 0ms
        - id: rating-route
          uri: http://rating-service:8085
          predicates:
            - Path=/api/ratings/**
