server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pokemon}"
    username: "${SPRING_DATASOURCE_USERNAME:pokemon}"
    password: "${SPRING_DATASOURCE_PASSWORD:pokemon}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
app:
  jwt:
    secret: "${JWT_SECRET:changeme-32-char-secret-for-dev-only}"
    expiration-hours: 24
  game-data:
    url: "${GAME_DATA_SERVICE_URL:http://localhost:8082}"
