apiVersion: apps/v1
kind: Deployment
metadata:
  name: battle-service
  namespace: poke-battle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: battle-service
  template:
    metadata:
      labels:
        app: battle-service
    spec:
      containers:
        - name: battle-service
          image: battle-service:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: poke-battle-config
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: battle-service
  namespace: poke-battle
spec:
  selector:
    app: battle-service
  ports:
    - port: 8084
      targetPort: 8084
