apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-service
  namespace: poke-battle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby-service
  template:
    metadata:
      labels:
        app: lobby-service
    spec:
      containers:
        - name: lobby-service
          image: lobby-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: poke-battle-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-service
  namespace: poke-battle
spec:
  selector:
    app: lobby-service
  ports:
    - port: 8083
      targetPort: 8083
