apiVersion: v1
kind: Secret
metadata:
  name: poke-battle-secrets
  namespace: poke-battle
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cG9rZW1vbg==
  JWT_SECRET: Y2hhbmdlbWUtMzItY2hhci1zZWNyZXQtZm9yLWRldi1vbmx5
  POSTGRES_PASSWORD: cG9rZW1vbg==
